# File: installer/answer-files/proxmox-answer.toml
# Proxmox VE 9.0 Automated Installation Answer File
# Single file works for both Dell OptiPlex nodes

[global]
# Keyboard and regional settings
keyboard = "us"                           # US keyboard layout
country = "au"                           # Australia for mirror selection
timezone = "Australia/Brisbane"          # Your correct timezone

# Network/system identification (will be changed post-install)
fqdn = "pve-temp.homelab.local"         # Temporary - post-install script changes this
mailto = "admin@homelab.local"          # Email for system alerts

# Temporary root password - gets locked by post-install script
root_password = "TempInstall2024!"      # Changed to SSH-key only post-install

[network]
# Network configuration for installation
# DHCP will assign IP and provide your Pi-hole DNS automatically
source = "from-dhcp"                    # Let DHCP handle IP, DNS, gateway
# Note: Post-install script will configure bonding and VLANs

[disk-setup]
# Disk selection and partitioning configuration
# This section is critical and hard to change after installation

# Filesystem type for root partition
# Options: ext4 (recommended), xfs, zfs (advanced), btrfs (experimental)
filesystem = "ext4"                      # Most reliable for homelab

# Disk selection strategy
disk_list = ["*"]                       # Select any available disk
                                       # Alternatives:
                                       # ["/dev/sda"] - specific disk
                                       # ["/dev/nvme0n1"] - specific NVMe
                                       # ["*SAMSUNG*"] - match by model
                                       
filter_match = "any"                   # Use first disk found that matches
                                       # "any" = use any disk from disk_list
                                       # "all" = all disks must match (for RAID)

[disk-setup.lvm]
# LVM (Logical Volume Manager) configuration
# Even with ext4, Proxmox uses LVM for flexibility
# All sizes in GB

total_size = "900"                     # Total space to use from disk (GB)
                                       # Leave ~100GB unallocated for:
                                       # - Over-provisioning (SSDs)
                                       # - Future expansion
                                       # - Emergency recovery space

swap_size = "8"                        # Swap partition size (GB)
                                       # Rule of thumb: 8GB for 32GB RAM
                                       # Used for hibernation and memory overflow

max_root_size = "100"                  # Maximum size for root filesystem (GB)
                                       # Contains: OS, applications, logs
                                       # 100GB is generous for Proxmox host OS

max_data_size = "792"                  # Maximum size for VM storage (GB)
                                       # This is where VMs and containers live
                                       # 792GB = 900 - 100 (root) - 8 (swap)

min_lvm_free = "16"                    # Minimum free space in volume group (GB)
                                       # Reserve for snapshots and expansion
                                       # Never allocate 100% of LVM space

# Final layout on your 1TB SSD will be approximately:
# - /dev/sda1: 1GB (EFI boot partition)
# - /dev/sda2: 900GB (LVM Physical Volume)
#   - swap: 8GB
#   - root: 100GB (Proxmox OS)
#   -  792GB (VM storage)
#   - free: 16GB (reserved)
# - Unallocated: ~99GB (SSD over-provisioning)
