---
# ansible/playbooks/register-host.yml

- name: Register New Host via MAC Lookup
  hosts: localhost
  connection: local
  gather_facts: true
  
  vars:
    primary_mac_input: "{{ primary_mac | lower }}"
    temp_ip_input: "{{ temp_ip }}"
    semaphore_url: "{{ SEMAPHORE_WEB_ROOT }}"
    semaphore_project_id: "{{ SEMAPHORE_PROJECT_ID }}"
    semaphore_inventory_id: "{{ SEMAPHORE_INVENTORY_ID }}"
    semaphore_api_token: "{{ SEMAPHORE_API_TOKEN }}"
  
  tasks:
    - name: Display registration request
      debug:
        msg: |
          Registration request received:
          - Primary MAC: {{ primary_mac_input }}
          - Temporary IP: {{ temp_ip_input }}
    
    - name: Find matching host in provisioning inventory
      set_fact:
        matched_host: >-
          {{
            hostvars | dict2items |
            selectattr('value.primary_interface.mac', 'defined') |
            selectattr('value.primary_interface.mac', 'equalto', primary_mac_input) |
            first | default({'key': 'not_found', 'value': {}})
          }}
    
    - name: Verify host was found
      assert:
        that:
          - matched_host.key != 'not_found'
          - matched_host.value.target_hostname is defined
        fail_msg: |
          ❌ MAC {{ primary_mac_input }} not found in provisioning inventory.
    
    - name: Extract host configuration
      set_fact:
        host_config: "{{ matched_host.value }}"
        target_hostname: "{{ matched_host.value.target_hostname }}"
    
    - name: Display identified host
      debug:
        msg: |
          ✓ Host identified:
          Hostname: {{ target_hostname }}
          Node ID: {{ host_config.node_id }}
          Target IP: {{ host_config.primary_interface.static_ip }}
    
    - name: Fetch production inventory
      uri:
        url: "{{ semaphore_url }}/api/project/{{ semaphore_project_id }}/inventory/{{ semaphore_inventory_id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ semaphore_api_token }}"
        return_content: yes
        status_code: 200
      register: current_inventory_response
    
    - name: Parse production inventory
      set_fact:
        current_inventory: "{{ current_inventory_response.json.inventory | from_yaml }}"
        inventory_meta "{{ current_inventory_response.json }}"
    
    - name: Ensure all.children exists
      set_fact:
        current_inventory: >-
          {{
            current_inventory | combine({
              'all': {
                'children': current_inventory.all.children | default({})
              }
            }, recursive=True)
          }}
    
    - name: Ensure primary target group exists
      set_fact:
        primary_group: "{{ host_config.target_groups[0] }}"
        current_inventory: >-
          {{
            current_inventory | combine({
              'all': {
                'children': current_inventory.all.children | combine({
                  host_config.target_groups[0]: {
                    'hosts': current_inventory.all.children[host_config.target_groups[0]].hosts | default({}),
                    'vars': {
                      'ansible_ssh_common_args': '-o StrictHostKeyChecking=no'
                    }
                  }
                })
              }
            }, recursive=True)
          }}
    
    # ===== FIX: Build host data first, then create entry with dynamic key =====
    - name: Build host configuration data
      set_fact:
        host_
          ansible_host: "{{ temp_ip_input }}"
          ansible_user: ansible
          ansible_python_interpreter: /usr/bin/python3
          lifecycle_state: registered
          registered_at: "{{ ansible_date_time.iso8601 }}"
          registered_by: first-boot-automation
          node_id: "{{ host_config.node_id }}"
          node_description: "{{ host_config.target_description }}"
          primary_mac: "{{ primary_mac_input }}"
          network_interfaces:
            primary: "{{ host_config.primary_interface }}"
            wifi: "{{ host_config.wifi_interface | default({}) }}"
            cluster: "{{ host_config.cluster_interface | default({}) }}"
          cluster_member: false
          target_cluster: "{{ host_config.target_cluster }}"
          cluster_role: "{{ host_config.target_role }}"
          storage_config: "{{ host_config.storage | default({}) }}"
          hardware: "{{ host_config.hardware | default({}) }}"
    
    - name: Create new host entry with target hostname as key
      set_fact:
        new_host_entry: "{{ {target_hostname: host_data} }}"
    
    # Debug to verify
    - name: Debug new host entry
      debug:
        msg: |
          New host entry:
          {{ new_host_entry | to_nice_yaml }}
    
    - name: Add new host to production inventory
      set_fact:
        updated_inventory: >-
          {{
            current_inventory | combine({
              'all': {
                'children': current_inventory.all.children | combine({
                  primary_group: {
                    'hosts': (current_inventory.all.children[primary_group].hosts | default({})) | combine(new_host_entry)
                  }
                })
              }
            }, recursive=True)
          }}
    
    - name: Update production inventory in Semaphore
      uri:
        url: "{{ semaphore_url }}/api/project/{{ semaphore_project_id }}/inventory/{{ semaphore_inventory_id }}"
        method: PUT
        headers:
          Authorization: "Bearer {{ semaphore_api_token }}"
          Content-Type: "application/json"
        body_format: json
        body: "{{ inventory_metadata | combine({'inventory': updated_inventory | to_nice_yaml}) }}"
        status_code: 204
        return_content: yes
      register: update_result
    
    - name: Trigger bootstrap playbook
      uri:
        url: "{{ semaphore_url }}/api/project/{{ semaphore_project_id }}/tasks"
        method: POST
        headers:
          Authorization: "Bearer {{ semaphore_api_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          template_id: 1
          message: "Bootstrap {{ target_hostname }}"
          environment: "{\"target_host\": \"{{ target_hostname }}\"}"
        status_code: 201
        return_content: yes
      register: bootstrap_task
    
    - name: Registration complete
      debug:
        msg: |
          ✓ Registration successful
          Hostname: {{ target_hostname }}
          Bootstrap task: {{ bootstrap_task.json.id }}
