---
# ansible/playbooks/register-host.yml
- name: Register New Host in Semaphore Inventory
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:
    # These come from the Variable Group in Semaphore
    semaphore_url: "{{ lookup('env', 'SEMAPHORE_WEB_ROOT') }}"
    semaphore_project_id: "{{ lookup('env', 'SEMAPHORE_PROJECT_ID') }}"
    semaphore_inventory_id: "{{ lookup('env', 'SEMAPHORE_INVENTORY_ID') }}"
    semaphore_api_token: "{{ lookup('env', 'SEMAPHORE_API_TOKEN') }}"
  
  tasks:
    - name: Debug - show all variables
      debug:
        var: hostvars[inventory_hostname]
    
    - name: Check if extra_vars were passed
      debug:
        msg: |
          Looking for:
          - new_hostname (value: {{ new_hostname | default('NOT DEFINED') }})
          - new_host_ip (value: {{ new_host_ip | default('NOT DEFINED') }})
          - new_host_group (value: {{ new_host_group | default('NOT DEFINED') }})
    
    - name: Set facts from extra_vars with defaults
      set_fact:
        hostname_input: "{{ new_hostname | default('unknown-host') }}"
        host_ip_input: "{{ new_host_ip | default('0.0.0.0') }}"
        host_group_input: "{{ new_host_group | default('uncategorized') }}"
        host_user_input: "{{ new_host_user | default('root') }}"
    
    - name: Display registration information
      debug:
        msg: |
          Registering new host:
          - Hostname: {{ hostname_input }}
          - IP Address: {{ host_ip_input }}
          - Group: {{ host_group_input }}
          - User: {{ host_user_input }}
